version: '3.8'

services:


  cockroachdb:
    image: cockroachdb/cockroach:v25.3.1
    container_name: cockroachdb
    restart: always
    ports:
      - "${DB_PORT:-26257}:26257"       
      - "8081:8080"              
    volumes:
      - cockroach-data:/cockroach/cockroach-data
    command: start-single-node --insecure
    networks:
      - app-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      args:
        API_PORT: ${API_PORT:-8080}                  
    container_name: hillary-mails-api
    restart: on-failure:3
    ports:
      - "${API_PORT:-8080}:${API_PORT:-8080}"
    env_file:
      - api/.env
    depends_on:
      - cockroachdb
    networks:
      - app-network
    volumes:
      - ./logs:/app/logs

  
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: hillary-mails-app
    ports:
      - "5173:80"
    depends_on:
      - api
    restart: on-failure:3
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  cockroach-data: