
 @url = http://localhost:8080/api

###
POST {{url}}/mails/search
Content-Type: application/json
{
    "query": "hillary",
    "type": "AND",
    "page": 1,
    "limit": 20,
    "dateSearch": {
        "date": "2019-07-01T06:00:00.000Z",
        "operator": "<="
    },
    "orderBy": "desc"
}

