services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vue-app
    env_file:
      - .env
    ports:
      - "3000:80"
    restart: always
    networks:
      - app-network