version: '3.8'

services:
  cockroachdb:
    image: cockroachdb/cockroach:v25.3.1
    container_name: cockroachdb
    restart: always
    ports:
      - "${DB_PORT:-26257}:26257"       
      - "8081:8080"              
    volumes:
      - cockroach-data:/cockroach/cockroach-data
    command: start-single-node --insecure
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        API_PORT: ${API_PORT:-8080}                  
    container_name: api
    restart: always
    ports:
      - "${API_PORT:-8080}:${API_PORT:-8080}"
    env_file:
      - .env
    depends_on:
      - cockroachdb
    networks:
      - app-network
    volumes:
      - ./logs:/app/logs

volumes:
  cockroach-data:
